# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  bitzen-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: bitzen-mysql
    volumes:
      - bitzen-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bitzen
      - MYSQL_DATABASE=bitzen
      - MYSQL_USER=bitzen
      - MYSQL_PASSWORD=bitzen

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: bitzen-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql